version: "3.9"
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234567890
      POSTGRES_DB: solar-ev-charger
    ports:
      - "7500:5432"
    volumes:
      - ./db-data:/var/lib/postgresql/data
    networks:
      - postgres

  solarbackend:
    build: ./solarbackend
    image: jrweqlop/nestjs-ecu-solar-charge
    container_name: solar-backend
    platform: linux/amd64
    restart: always
    # depends_on:
    #   - db
    environment:
      - DATABASE_URL=postgresql://postgres:1234567890@db:5432/solar-ev-charger?schema=public
      # - DATABASE_URL=postgresql://root:WXkf1IzJrqmvF3kiVUUtkfbq1YbGq14g@dpg-cvn17r7gi27c73beoba0-a.oregon-postgres.render.com/ecusolarcharge
    ports:
      - "7550:4500"
      - "7755:81"
    networks:
      - postgres
  web:
    build:
      context: ./webview
      args:
        NEXT_PUBLIC_WS_CONNECT: ws://3.107.193.91:7755/device
    image: nextjs-solar-webview
    container_name: solar-web-view
    platform: linux/amd64
    restart: always
    environment:
      - NEXT_PUBLIC_WS_CONNECT=ws://3.107.193.91:7755/device
    ports:
      - "3000:3000"

networks:
  postgres:
    driver: bridge
