version: "3.9"
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234567890
      POSTGRES_DB: solar-ev-charger
    ports:
      - "7500:5432"
    volumes:
      - ./db-data:/var/lib/postgresql/data
    networks:
      - postgres

  solarbackend:
    build: ./solarbackend
    image: jrweqlop/nestjs-ecu-solar-charge
    container_name: solar-backend
    platform: linux/amd64
    restart: always
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://postgres:1234567890@db:5432/solar-ev-charger?schema=public
    ports:
      - "7550:4500"
    networks:
      - postgres

networks:
  postgres:
    driver: bridge
